### ISSUE TITLE
How will this application get initial data

### ISSUE THREAD

**Issue by Airmagic** [LincT/lmn#7]
How will this application get initial data? 
At the moment, shows, venues, and artists must be added through the administrator console.  Focus on the Twin Cities and figure out a programatic method of getting data for shows, (ideas: write a web scraper for First-Avenue.com and other popular venues, or maybe there's an API you can use?)

**Comment by JustinGJohnson** [comment]
Added myself to this issue to help Jeremy with it.

**Comment by pi6220na** [comment]
This function, a web-scrapper/db loader/api, has been moved to pi6220na/lmn_api. Closing as no longer needed in this repo. - Jeremy
